services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_MODE: production
    container_name: weekly_dev_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/weekly-dev
    depends_on:
      - mysql
      - httpd
      - floci
      - mailhog
    networks:
      - weekly_dev_network

  httpd:
    build:
      context: .
      dockerfile: ./docker/httpd/Dockerfile
    container_name: weekly_dev_httpd
    restart: unless-stopped
    volumes:
      - ./:/var/www/weekly-dev
      - ./docker/httpd/vhosts.conf:/etc/apache2/sites-available/vhosts.conf
    depends_on:
      - mysql
      - floci
      - mailhog
    networks:
      - weekly_dev_network

  mysql:
    image: mysql:8.0.36
    container_name: weekly_dev_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: weekly_dev
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - weekly_dev_database:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - weekly_dev_network

  floci:
    image: floci/floci:latest
    container_name: weekly_dev_floci
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FLOCI_HOSTNAME: floci
      FLOCI_SERVICES_DOCKER_NETWORK: weekly_dev_network
    networks:
      - weekly_dev_network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: weekly_dev_mailhog
    restart: unless-stopped
    networks:
      - weekly_dev_network

networks:
  weekly_dev_network:
    driver: bridge

volumes:
  weekly_dev_database: